-- [ 뷰(VIEW) 연습문제 ]
-- 연습 1) 20번 부서에 소속된 사원의 사원 번호와 이름과 부서 번호를 출력하는 VIEW를 정의하기
CREATE OR REPLACE VIEW VW_EMP_TEST01
AS
SELECT EMPNO, ENAME, DEPTNO
FROM EMP
WHERE DEPTNO LIKE 20;

-- 연습 2) 이미 생성되어 있는 상기 뷰에 대해 급여 또한 출력하도록 수정하기
CREATE OR REPLACE VIEW VW_EMP_TEST01
AS
SELECT EMPNO, ENAME, DEPTNO, SAL
FROM EMP
WHERE DEPTNO LIKE 20;

ALTER TABLE EMPLOYEE RENAME COLUMN DEPTNO TO DNO;